"""Shared utilities for NNnGP HMC/VI experiments."""

import os
import numpy as np
import jax
import jax.numpy as jnp

from model import g_matern32_kernel_jax

np.set_printoptions(precision=6, suppress=True)


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)
    return path


def sanitize_true_params(true_params):
    """Convert numpy object-array params into Python/numpy values."""
    return {
        "matern_params": tuple(float(x) for x in true_params["matern_params"]),
        "tau_params": tuple(float(x) for x in true_params["tau_params"]),
        "g_params": tuple(float(x) for x in true_params["g_params"]),
        "beta": np.asarray(true_params["beta"], dtype=np.float64),
        "sigma_epsilon": float(true_params["sigma_epsilon"]),
        "m": int(true_params["m"]),
        "m_tilde": int(true_params["m_tilde"]),
    }


def load_synthetic_data(data_path=None):
    """Load synthetic data generated by data_utils.py."""
    if data_path is None:
        try:
            from data_utils import RESULTS_DIR
            data_path = os.path.join(RESULTS_DIR, "test_synthetic_data.npz")
        except Exception:
            data_path = os.path.join("results", "data_utils_outputs", "test_synthetic_data.npz")
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"未找到数据文件: {data_path}. 请先运行 python data_utils.py")

    try:
        from data_utils import load_data
        data = load_data(data_path)
    except Exception:
        raw = np.load(data_path, allow_pickle=True)
        data = {key: raw[key] for key in raw.files}
        if isinstance(data.get("true_params"), np.ndarray):
            data["true_params"] = data["true_params"].item()
    data["true_params"] = sanitize_true_params(data["true_params"])
    return data, data_path


def make_parent_matern_kernel(params):
    from sklearn.gaussian_process.kernels import Matern
    sigma_f, length_scale = params["matern_params"]
    return (sigma_f ** 2) * Matern(length_scale=length_scale, nu=1.5)


def precompute_RZ(Z, rho, jitter=1e-6):
    Z_jax = jnp.asarray(Z, dtype=jnp.float64)
    R_Z = g_matern32_kernel_jax(Z_jax, Z_jax, rho) + jitter * jnp.eye(Z_jax.shape[0], dtype=jnp.float64)
    R_Z_inv = jnp.linalg.inv(R_Z)
    return np.asarray(R_Z), np.asarray(R_Z_inv)


def z_to_w_samples(z_samples, L):
    """Convert z = T w into w = T^{-1} z."""
    L = jnp.asarray(L, dtype=jnp.float64)
    z_samples = jnp.asarray(z_samples, dtype=jnp.float64)
    w_samples = jax.vmap(lambda z: jax.scipy.linalg.solve_triangular(L, z, lower=True, trans="N"))(z_samples)
    return np.asarray(w_samples)
